name: android

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      ndk_ver:
        description: 'Specific the ndk version, i.e. r16b, r19c or later'
        # Default value if no value is explicitly provided
        default: 'r16b+'
        # Input has to be provided for the workflow to run
        required: false

env:
  NDK_VER: ${{github.event.inputs.ndk_ver}} # r16b can't runs on ubuntu latest, test works on ubuntu-18.04

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    strategy:
      matrix:
        arch:
          - armv7
          - arm64
          - x86
          - x64
    env:
      BUILD_ARCH: ${{ matrix.arch }}
      
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      shell: pwsh
      run: ./build.ps1 -p android -a $env:BUILD_ARCH
    
    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release ${{ steps.tag.outputs.result }}
        draft: false
        artifacts: "./
        allowUpdates: true
